"""Inline keyboard builders and callback identifiers."""

from app.bot.keyboards import callbacks
from app.bot.keyboards.bank import (
    build_bank_cancel,
    build_bank_history,
    build_bank_menu,
    build_transfer_confirmation,
    build_transfer_recipient_confirmation,
)
from app.bot.keyboards.crime import (
    build_crime_cancel,
    build_crime_history,
    build_crime_menu,
    build_document_menu,
    build_shoti_vehicle_menu,
)
from app.bot.keyboards.business import (
    build_business_list,
    build_business_menu,
    build_owned_businesses,
)
from app.bot.keyboards.iran_market import (
    build_iran_market_detail,
    build_iran_market_menu,
)
from app.bot.keyboards.divar import (
    build_divar_categories,
    build_divar_city_filters,
    build_divar_filters,
    build_divar_listing_detail,
    build_divar_menu,
    build_divar_my_listings,
    build_divar_owned_assets,
    build_divar_results,
)
from app.bot.keyboards.vehicle import (
    build_owned_vehicle_detail,
    build_owned_vehicles,
    build_vehicle_catalog,
    build_vehicle_confirmation,
    build_vehicle_menu,
    build_vehicle_model_detail,
)
from app.bot.keyboards.housing import (
    build_buy_confirmation,
    build_house_info,
    build_housing_menu,
    build_market_list,
    build_my_houses,
    build_my_rents,
    build_rent_confirmation,
    build_rent_options,
    build_rentals_list,
    build_sale_price_options,
)
from app.bot.keyboards.main_menu import (
    BUTTON_BANK,
    BUTTON_CRIME,
    BUTTON_BUSINESS,
    BUTTON_DIVAR,
    BUTTON_HOUSING,
    BUTTON_VEHICLE_DEALERSHIP,
    BUTTON_IRAN_MARKET,
    build_back_to_main,
    build_jobs_list,
    build_jobs_menu,
    build_main_menu,
)

__all__ = [
    "callbacks",
    "build_bank_menu",
    "build_bank_cancel",
    "build_crime_menu",
    "build_crime_cancel",
    "build_crime_history",
    "build_document_menu",
    "build_shoti_vehicle_menu",
    "build_bank_history",
    "build_transfer_confirmation",
    "build_transfer_recipient_confirmation",
    "build_back_to_main",
    "build_main_menu",
    "build_business_menu",
    "build_business_list",
    "build_owned_businesses",
    "build_iran_market_menu",
    "build_iran_market_detail",
    "build_divar_menu",
    "build_divar_categories",
    "build_divar_city_filters",
    "build_divar_filters",
    "build_divar_listing_detail",
    "build_divar_my_listings",
    "build_divar_owned_assets",
    "build_divar_results",
    "build_vehicle_menu",
    "build_vehicle_catalog",
    "build_vehicle_model_detail",
    "build_vehicle_confirmation",
    "build_owned_vehicles",
    "build_owned_vehicle_detail",
    "build_jobs_menu",
    "build_jobs_list",
    "BUTTON_BUSINESS",
    "BUTTON_BANK",
    "BUTTON_CRIME",
    "BUTTON_DIVAR",
    "BUTTON_VEHICLE_DEALERSHIP",
    "BUTTON_IRAN_MARKET",
    "BUTTON_HOUSING",
    "build_housing_menu",
    "build_market_list",
    "build_rentals_list",
    "build_my_houses",
    "build_my_rents",
    "build_house_info",
    "build_buy_confirmation",
    "build_rent_confirmation",
    "build_sale_price_options",
    "build_rent_options",
]
